name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: BellaFGS
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generated snake'
          add: 'github-contribution-grid-snake.svg'
